### PR TITLE
Split GameOfLife out a bit (this time after merging in the change made since I forked)

### PR DESCRIPTION
**Pull request by beresfordt**
Hi,

Saw the thread on reddit and thought I'd have a tinker. To make it easier to test and expand I've separated out GameOfLife into a set of classes which have more discrete responsibilities. There's still more coupling than I think is needed, but it's a start. I've also altered the directory structure a little so that it's more like the maven directory structure, giving a good starting point from which tests can be introduced etc

If you have any questions or suggestions for how to get this pull request into a shape you would prefer please let me know

Tom

### CODE REVIEW

**Comment by mehalter** [comment]
This looks great! Thanks, I will pull and merge it now. I was doing some tinkering in splitting up the classes, but this is great!

**Comment by beresfordt** [comment]
I'm kind of tempted to pass GameState to GamePanel rather than having panel owning the xSize, ySize grid etc; what do you think?

**Comment by mehalter** [comment]
What do you mean when you say pass the GameState to GamePanel?

**Comment by beresfordt** [comment]
Just after typing all the below I noticed that in my above comment I said GamePanel, but meant GridPanel..

GridPanel has fields which are to do with the state of the game; xSize, ySize, grid, user1, user2. Rather than GridPanel, which is a swing JPanel, holding this state (and having all the associated getters and setters) I think we could add these fields to GameState and make GameState the sole constructor argument for GridPanel

**Comment by beresfordt** [comment]
Hmm; though given the current model GameState would seem to be the correct place for xSize, ySize, grid, user1, user2 I'm not convinced that GameState should actually exist. It was a useful step while separating out the classes, but I'm not convinced of it's value any more

**Comment by mehalter** [comment]
I see what you mean when you say you don't see its value. After I moved those variables over to GameState, it was apparent how unnecessary splitting that into two files is. Not particularly the GameState file, but having them separate didn't make sense anymore. I merged the two which basically tells GameState how to draw itself.  Not quite sure if this is the best way or not, or if it should be GridPanel. Let me know what you think.

**Comment by beresfordt** [comment]
GridPanel is there to display the underlying state of the game of life grid; were there to be different ways of displaying that state we should certainly have a separate class to represent that state; eg if there was to be a web version.

As writing to file is writing the state to a file I'm leaning towards there being a class which holds the state; the filewriter can then persist that to file, the GridPanel can draw it via swing.

Once the grid variables are moved to GameState I think that the GridPanel field of GameState should probably belong to GameOfLifeUi; once its responsibility is just representing the current state, rather than storing it, it is just part of the UI

Will make the above changes and submit a pull request so you can see what I mean; I express myself more clearly in code than in text

**Comment by beresfordt** [comment]
So I was thinking something like https://github.com/beresfordt/Multiplayer-Game-of-Life/tree/GridPanelRefactor

**Comment by mehalter** [comment]
Ok, yeah I see what you mean. I had something like that before I merged the two.

**Comment by mehalter** [comment]
Could you submit that as a pull request, and I will merge it with the master branch?

**Pull request merged**
